services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL_FOR_BROWSER}
    ports:
      - "8082:8082"
    networks:
      - agentsofrevature-p2-backend_app-network

networks:
  agentsofrevature-p2-backend_app-network:
    external: true