services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://app:8081
    networks:
      - agentsofrevature-p2-backend_app-network

networks:
  agentsofrevature-p2-backend_app-network:
    external: true 