/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicSignUpImport } from './routes/(public)/sign-up'
import { Route as publicSignInImport } from './routes/(public)/sign-in'
import { Route as publicLayoutImport } from './routes/(public)/_layout'
import { Route as protectedProfileImport } from './routes/(protected)/profile'
import { Route as protectedHomeImport } from './routes/(protected)/home'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const publicSignUpRoute = publicSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRoute,
} as any)

const publicSignInRoute = publicSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRoute,
} as any)

const publicLayoutRoute = publicLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => publicRoute,
} as any)

const protectedProfileRoute = protectedProfileImport.update({
  id: '/(protected)/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const protectedHomeRoute = protectedHomeImport.update({
  id: '/(protected)/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/home': {
      id: '/(protected)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedHomeImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicLayoutImport
      parentRoute: typeof publicRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInImport
      parentRoute: typeof publicImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpImport
      parentRoute: typeof publicImport
    }
  }
}

// Create and export the route tree

interface publicRouteChildren {
  publicLayoutRoute: typeof publicLayoutRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicRouteChildren: publicRouteChildren = {
  publicLayoutRoute: publicLayoutRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/home': typeof protectedHomeRoute
  '/profile': typeof protectedProfileRoute
  '/': typeof publicLayoutRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
}

export interface FileRoutesByTo {
  '/home': typeof protectedHomeRoute
  '/profile': typeof protectedProfileRoute
  '/': typeof publicLayoutRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(protected)/home': typeof protectedHomeRoute
  '/(protected)/profile': typeof protectedProfileRoute
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_layout': typeof publicLayoutRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/profile' | '/' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/profile' | '/' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/(protected)/home'
    | '/(protected)/profile'
    | '/(public)'
    | '/(public)/_layout'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  protectedHomeRoute: typeof protectedHomeRoute
  protectedProfileRoute: typeof protectedProfileRoute
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  protectedHomeRoute: protectedHomeRoute,
  protectedProfileRoute: protectedProfileRoute,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(protected)/home",
        "/(protected)/profile",
        "/(public)"
      ]
    },
    "/(protected)/home": {
      "filePath": "(protected)/home.tsx"
    },
    "/(protected)/profile": {
      "filePath": "(protected)/profile.tsx"
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_layout",
        "/(public)/sign-in",
        "/(public)/sign-up"
      ]
    },
    "/(public)/_layout": {
      "filePath": "(public)/_layout.tsx",
      "parent": "/(public)"
    },
    "/(public)/sign-in": {
      "filePath": "(public)/sign-in.tsx",
      "parent": "/(public)"
    },
    "/(public)/sign-up": {
      "filePath": "(public)/sign-up.tsx",
      "parent": "/(public)"
    }
  }
}
ROUTE_MANIFEST_END */
